#!/usr/bin/env bash
# Generate and install coherent mode7 WGP masks for BC-250 extra WGP testing.

set -euo pipefail

CONF="${BC250_MODE7_CONF:-/etc/modprobe.d/bc250-40cu.conf}"
ALL_EXTRAS="${BC250_EXTRA_WGPS:-0.0.3 0.0.4 0.1.3 0.1.4 1.0.3 1.0.4 1.1.3 1.1.4}"

usage() {
	cat <<EOF
Usage:
  ./scripts/bc250-mode7-mask.sh status
  ./scripts/bc250-mode7-mask.sh module-check
  ./scripts/bc250-mode7-mask.sh plan-extra-set SE.SH.WGP[,SE.SH.WGP...]
  sudo ./scripts/bc250-mode7-mask.sh apply-extra-set SE.SH.WGP[,SE.SH.WGP...]
  sudo ./scripts/bc250-mode7-mask.sh apply-disable-set SE.SH.WGP[,SE.SH.WGP...]
  sudo ./scripts/bc250-mode7-mask.sh baseline
  sudo ./scripts/bc250-mode7-mask.sh disable

mode7 uses coherent CC/SPI/RLC masks and treats only WGP 3/4 in each shader
array as selectable extras. The stock 24 CUs stay enabled.

Examples:
  ./scripts/bc250-mode7-mask.sh plan-extra-set 0.0.4,0.1.4,1.0.4,0.1.3,1.0.3,1.1.3
  sudo ./scripts/bc250-mode7-mask.sh apply-extra-set 0.0.4,0.1.4,1.0.4,0.1.3,1.0.3,1.1.3
  sudo ./scripts/bc250-mode7-mask.sh baseline
EOF
}

die() {
	echo "ERROR: $*" >&2
	exit 1
}

need_root() {
	[ "$(id -u)" = "0" ] || die "this command requires root"
}

join_csv() {
	local IFS=,
	echo "$*"
}

validate_extra() {
	local item="$1"
	[[ "$item" =~ ^[0-1]\.[0-1]\.[3-4]$ ]] ||
		die "invalid extra WGP: $item"
}

split_csv_to_array() {
	local csv="${1:-none}"
	local -n out_ref="$2"
	local item

	out_ref=()
	[ "$csv" != "none" ] || return 0
	[ -n "$csv" ] || return 0

	IFS=',' read -ra out_ref <<<"$csv"
	for item in "${!out_ref[@]}"; do
		out_ref[$item]="${out_ref[$item]//[[:space:]]/}"
		[ -n "${out_ref[$item]}" ] || die "empty WGP entry in CSV: $csv"
		validate_extra "${out_ref[$item]}"
	done
}

normalize_active_csv() {
	local csv="${1:-none}"
	local -a items=()
	local -A seen=()
	local -a normalized=()
	local item extra

	split_csv_to_array "$csv" items
	for item in "${items[@]}"; do
		local known=0
		for extra in $ALL_EXTRAS; do
			validate_extra "$extra"
			if [ "$item" = "$extra" ]; then
				known=1
				break
			fi
		done
		[ "$known" = "1" ] || die "extra WGP is not in BC250_EXTRA_WGPS: $item"
		if [ -z "${seen[$item]+x}" ]; then
			seen["$item"]=1
			normalized+=("$item")
		fi
	done

	if [ "${#normalized[@]}" -eq 0 ]; then
		echo "none"
	else
		join_csv "${normalized[@]}"
	fi
}

disabled_csv_for_active() {
	local active_csv
	local -a active_items=()
	local -A active=()
	local -a disabled=()
	local item extra

	active_csv="$(normalize_active_csv "${1:-none}")"
	split_csv_to_array "$active_csv" active_items
	for item in "${active_items[@]}"; do
		active["$item"]=1
	done
	for extra in $ALL_EXTRAS; do
		validate_extra "$extra"
		if [ -z "${active[$extra]+x}" ]; then
			disabled+=("$extra")
		fi
	done

	join_csv "${disabled[@]}"
}

active_csv_for_disabled() {
	local disabled_csv="${1:-none}"
	local -a disabled_items=()
	local -A disabled=()
	local -a active=()
	local item extra

	split_csv_to_array "$disabled_csv" disabled_items
	for item in "${disabled_items[@]}"; do
		disabled["$item"]=1
	done
	for extra in $ALL_EXTRAS; do
		validate_extra "$extra"
		if [ -z "${disabled[$extra]+x}" ]; then
			active+=("$extra")
		fi
	done

	if [ "${#active[@]}" -eq 0 ]; then
		echo "none"
	else
		join_csv "${active[@]}"
	fi
}

extra_count() {
	local active_csv
	local -a active_items=()

	active_csv="$(normalize_active_csv "${1:-none}")"
	split_csv_to_array "$active_csv" active_items
	echo "${#active_items[@]}"
}

expected_num_cu() {
	echo $((24 + 2 * $(extra_count "${1:-none}")))
}

module_supports_mode7() {
	modinfo amdgpu 2>/dev/null |
		awk '/bc250_cc_write_mode/ && /7=coherent-disable-cus/ { found = 1 } END { exit found ? 0 : 1 }'
}

config_text_for_active() {
	local active_csv disabled_csv generated_by

	active_csv="$(normalize_active_csv "${1:-none}")"
	disabled_csv="$(disabled_csv_for_active "$active_csv")"
	generated_by="$(basename "$0")"

	echo "# BC-250 coherent selective extra-WGP mask."
	echo "# Active extra WGPs: $active_csv"
	echo "# Disabled extra WGPs: ${disabled_csv:-none}"
	echo "# Generated by $generated_by on $(date -Iseconds)."
	echo "# Requires patched amdgpu with bc250_cc_write_mode=7."
	if [ -n "$disabled_csv" ]; then
		echo "options amdgpu bc250_cc_write_mode=7 disable_cu=$disabled_csv"
	else
		echo "options amdgpu bc250_cc_write_mode=7"
	fi
}

refresh_initramfs() {
	if command -v update-initramfs >/dev/null 2>&1; then
		update-initramfs -u -k "$(uname -r)" || true
	elif command -v dracut >/dev/null 2>&1; then
		dracut -f || true
	fi
}

install_active() {
	local active_csv
	local tmp

	need_root
	active_csv="$(normalize_active_csv "${1:-none}")"
	tmp="$(mktemp)"
	trap 'rm -f "$tmp"' RETURN
	config_text_for_active "$active_csv" >"$tmp"
	install -m 0644 "$tmp" "$CONF"
	refresh_initramfs
	echo "installed_config=$CONF"
	echo "active_extra_wgps=$active_csv"
	echo "disabled_extra_wgps=$(disabled_csv_for_active "$active_csv")"
	echo "expected_num_cu=$(expected_num_cu "$active_csv")"
}

plan_extra_set() {
	local active_csv

	active_csv="$(normalize_active_csv "${1:-none}")"
	echo "active_extra_wgps=$active_csv"
	echo "disabled_extra_wgps=$(disabled_csv_for_active "$active_csv")"
	echo "expected_num_cu=$(expected_num_cu "$active_csv")"
	echo
	echo "modprobe_config:"
	config_text_for_active "$active_csv"
}

show_status() {
	echo "config_file=$CONF"
	echo
	echo "kernel_parameter:"
	cat /sys/module/amdgpu/parameters/bc250_cc_write_mode 2>/dev/null || echo "unavailable"
	echo
	echo "modprobe_config:"
	if [ -f "$CONF" ]; then
		sed -n '1,120p' "$CONF"
	else
		echo "none"
	fi
	echo
	echo "vulkan:"
	if command -v vulkaninfo >/dev/null 2>&1; then
		RADV_DEBUG=info vulkaninfo --summary 2>&1 |
			grep -E 'num_cu|num_cu_per_sh|deviceName|driverName|driverInfo' |
			sed -n '1,120p' || true
	else
		echo "vulkaninfo not found"
	fi
}

disable_config() {
	need_root
	rm -f "$CONF"
	refresh_initramfs
	echo "removed_config=$CONF"
}

case "${1:-}" in
	status)
		show_status
		;;
	module-check)
		if module_supports_mode7; then
			echo "mode7_supported=yes"
		else
			echo "mode7_supported=no"
			exit 1
		fi
		;;
	plan-extra-set)
		plan_extra_set "${2:-none}"
		;;
	apply-extra-set)
		install_active "${2:-none}"
		;;
	apply-disable-set)
		install_active "$(active_csv_for_disabled "${2:-none}")"
		;;
	baseline)
		install_active none
		;;
	disable)
		disable_config
		;;
	-h|--help|"")
		usage
		;;
	*)
		usage >&2
		exit 2
		;;
esac
